### ISSUE TITLE
Prepend selector for multiple selectors

### ISSUE THREAD

**Issue by darielnoel** [ledniy/postcss-prepend-selector#1]
Hi, thanks for this project, I was playing with it today and I think that is useful. However there are an issue related to the multiple selectors. For example:

``` css
.a , .b, .c{
}
```

The output is:

``` css
#prepend .a , .b, .c{
}
```

I took a look to the code and seems to be related to this line:

``` js
rule.selector = opts.selector + rule.selector;
```

We could validate this kind of selectors, Actually I don't know if postcss has an API to make this validation easier.  Unfurtunately I don't have time to find the better solution. I'm sorry

Best Regards, Dariel

**Comment by ledniy** [comment]
@darielnoel thx u for feedback, i fixed that in https://github.com/ledniy/postcss-prepend-selector/commit/544cb65a54895cde636609fb655e0d517bc2333b
